services:
  inference_api:
    build:
      context: .
      dockerfile: Dockerfile.inference_api
    ports:
      - "8063:8063"
    restart: always

  chat_app:
    build:
      context: .
      dockerfile: Dockerfile.chat_app
    ports:
      - "8501:8501"
    restart: always