# chat_app/Dockerfile

FROM python:3.10-slim

WORKDIR /app

COPY ../requirements.txt ./requirements.txt
COPY . .

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "chat_app/app.py", "--server.port=8501", "--server.address=0.0.0.0"]